Added programmer names into csv external file
pagopa/pivotal-stories pull request #5
Opened 2021-02-05 17:45 UTC by pasqualespica

This PR proposes to read programmer list names from external file

#### List of Changes

- Updated script `pair_programming.py` to read external file  `programmers.csv`
- Added  `programmers.csv` with all `PagoPa`'s programmers involved into pair-programming

#### Motivation and Context

This  PR allows to add and delete people from pair programming list without modifying the script that creates shuffle on `pivotal`

#### How Has This Been Tested?

Run it locally  typing `python pair_programming.py` and print `get_pair_programming_message()`

2021-02-05 19:33 UTC, Undermaken requested changes

2021-02-05 19:33 UTC, Undermaken commented on src/utils/pair_programming.py
> +    with open('programmers.csv') as csv_file:
Same of above: could it be `developers.csv`?

2021-02-07 15:25 UTC, Undermaken requested changes

2021-02-07 15:25 UTC, Undermaken commented on src/utils/pair_programming.py
> +    with open('developers.csv') as csv_file:
If you run main.py it raises an error

```python
Traceback (most recent call last):
  File ".../pivotal/src/main.py", line 4, in <module>
    from utils.pair_programming import get_pair_programming_message
  File ".../pivotal/src/utils/pair_programming.py", line 24, in <module>
    developers = read_developers()
  File ".../pivotal/src/utils/pair_programming.py", line 14, in read_developers
    with open('developers.csv') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'developers.csv'
```

Since it tries to load a local `developers.csv` file while it is in `utils/developers.csv`
Perhaps could it be placed in a `data` folder?

I tested, and it works
```suggestion
    with open('./data/developers.csv') as csv_file:
```

2021-02-08 08:30 UTC, pasqualespica commented on src/utils/pair_programming.py
> +    with open('developers.csv') as csv_file:
it's right. Tnx for tip

2021-02-08 09:51 UTC, Undermaken approved these changes

2021-02-08 09:51 UTC, merged